"""
Django settings for warehouse project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from decouple import config

env = config("ENV", "Local")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY", "Local e$&$xp0gc5wep%95=_s#@+m-s+9pp^*rx%7r+d+$iatu#0opav"
)

# SECURITY WARNING: don't run with debug turned on in production!
if env == "PROD":
    DEBUG = False
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    DEBUG = True
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# ALLOWED_HOSTS = config('ALLOWED_HOSTS',["*"])
ALLOWED_HOSTS = [
    "*",
]
CORS_ORIGIN_ALLOW_ALL = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "wareApp",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware early
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",  # Add this line
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "warehouse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "warehouse.wsgi.application"
SETTINGS_PATH = os.path.normpath(os.path.dirname(__file__))

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASE_ROUTERS = ["wareApp.routers.SecondaryDBRouter"]
if env == "Local":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_HOSTNAME"),
            "USER": config("DB_USERNAME"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT"),
            "CONN_MAX_AGE": 60,
        }
        # "secondary": {
        #     "ENGINE": "django.db.backends.postgresql_psycopg2",
        #     "NAME": "warehouse",
        #     "USER": "aviconn",
        #     "PASSWORD": "1V3asem2025",
        #     "HOST": "43.204.53.81",
        #     "PORT": "5432",
        # },
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }

AUTH_USER_MODEL = "wareApp.User"
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_L10N = True

USE_TZ = False

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
print("BASE_DIR, : ", BASE_DIR)
print("STATIC_ROOT : ", STATIC_ROOT)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", "")
EMAIL_HOST = config("EMAIL_HOST", "")
EMAIL_HOST_USER = config("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", "")
EMAIL_PORT = config("EMAIL_PORT", "")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", "")
EMAIL_BACKEND = config("EMAIL_BACKEND", "")
# ADMINS = [('gyan', 'gyanender@aviconn.in')]

# CELERY STUFF
# BROKER_URL = 'redis://avc1.aviconn.in:6379'
# BROKER_URL = 'redis://locathost:6379'
# BROKER_TRANSPORT = 'redis'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# CELERYBEAT_SCHEDULER='djcelery'

# SECURE_PROXY_SSL_HEADER         = None
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# CSRF_COOKIE_SECURE = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "5/minute", "user": "1000/minute"},
}

LOG_FILE = f"{BASE_DIR}/logges"
# Recovery / Redis settings
# Enable Redis-backed recovery coalescing (set to False to use in-process queue)
RECOVERY_USE_REDIS = True
# Redis URL for recovery data (separate DB recommended)
REDIS_URL = config("REDIS_URL", "redis://localhost:6379/1")
# How long to keep the latest payload in seconds (default: 1 hour)
RECOVERY_PAYLOAD_TTL = config("RECOVERY_PAYLOAD_TTL", 3600, cast=int)
# How long the pending flag persists to prevent duplicate queue pushes (default: 1 hour)
RECOVERY_PENDING_TTL = config("RECOVERY_PENDING_TTL", 3600, cast=int)
# Redis queue name for recovery keys
RECOVERY_QUEUE_NAME = config("RECOVERY_QUEUE_NAME", "recovery:queue:v1")
# How many worker threads to start for recovery processing (Redis or in-process)
RECOVERY_WORKER_CONCURRENCY = config("RECOVERY_WORKER_CONCURRENCY", 1, cast=int)
# Enable Prometheus metrics for recovery (if prometheus_client is installed)
RECOVERY_ENABLE_METRICS = config("RECOVERY_ENABLE_METRICS", False, cast=bool)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime}|{levelname}|{module}|{process:d}--{thread:d}|{message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": f"{LOG_FILE}/debug.log",
            "formatter": "verbose",
        },
        "recovery_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": f"{LOG_FILE}/recovery.log",
            "formatter": "verbose",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "propagate": True,
        },
        "django.request": {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "wareApp.recovery": {
            "handlers": ["recovery_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         },
#     }
# }


SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
