# Generated by Django 2.2.2 on 2022-10-08 13:33

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserType', models.PositiveIntegerField(choices=[(1, 'Super_Admin'), (2, 'Aviconn_Admin'), (3, 'Aviconn_Executive'), (4, 'Customer'), (5, 'Cust_Site_Manager')], default=1)),
                ('Contact_number', models.CharField(help_text='Enter the contact number', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AisleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_leg_id', models.CharField(blank=True, max_length=30, null=True)),
                ('aisleGroupName', models.CharField(max_length=100)),
                ('total_lights', models.IntegerField(blank=True, null=True)),
                ('one_light_watt', models.IntegerField(blank=True, null=True)),
                ('expected_consumption', models.FloatField(blank=True, null=True)),
                ('cumulative_consumption', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('visible_date', models.DateField(blank=True, null=True)),
                ('is_this_power_source', models.BooleanField(default=False)),
                ('power_source', models.PositiveIntegerField(choices=[(0, 'MAINS SUPPLY'), (1, 'DG '), (2, 'DG 1'), (3, 'DG 2'), (4, 'DG 3'), (5, 'DG 4')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AisleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('aisle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('total_energy_consumed', models.FloatField(default=0)),
                ('total_energy_saved', models.FloatField(default=0)),
                ('total_sites', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LightsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(blank=True, max_length=40, null=True)),
                ('totalLights', models.IntegerField(blank=True, null=True)),
                ('watt_18_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_20_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_24_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_36_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_40_Lights', models.IntegerField(blank=True, null=True)),
                ('totalWattLights', models.IntegerField(blank=True, null=True)),
                ('totalUnits', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_meterId', models.PositiveIntegerField(blank=True, null=True)),
                ('reading_for', models.PositiveIntegerField(blank=True, choices=[(0, 'Energy'), (1, 'Load_time'), (2, 'Sensor')], null=True)),
                ('reading_of', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_reading_value', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=5, null=True)),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=10)),
                ('sensor_status', models.BooleanField()),
                ('sensor_on_date_time', models.DateTimeField()),
                ('sensor_off_date_time', models.DateTimeField()),
                ('sensor_associated_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_type', models.PositiveIntegerField(blank=True, choices=[(1, 'WH_Metering'), (2, 'WH_Energy_Saving'), (3, 'Fire_monitoring_system'), (4, 'FEMS')], null=True)),
                ('total_no_of_blocks', models.PositiveIntegerField(blank=True, null=True)),
                ('total_no_of_aisles', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('per_unit_cost', models.FloatField(blank=True, null=True)),
                ('genset_unit_rate', models.FloatField(blank=True, null=True)),
                ('no_of_single_source_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_dual_source_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_visible', models.BooleanField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('live_date', models.DateTimeField(blank=True, null=True)),
                ('current_baseline', models.FloatField(blank=True, null=True)),
                ('consumed_energy', models.FloatField(blank=True, null=True)),
                ('total_energy_saved', models.FloatField(blank=True, null=True)),
                ('avg_saving', models.FloatField(blank=True, null=True)),
                ('max_saving', models.FloatField(blank=True, null=True)),
                ('min_saving', models.FloatField(blank=True, null=True)),
                ('max_threshold_value', models.FloatField(blank=True, null=True)),
                ('min_threshold_value', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to=settings.AUTH_USER_MODEL)),
                ('site_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyLoadTimeShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_source', models.PositiveSmallIntegerField(choices=[(0, 'MAINS SUPPLY'), (1, 'DG 1'), (2, 'DG 2'), (3, 'DG 3'), (4, 'DG 4'), (5, 'DG 5')], default=0)),
                ('hourly_run_time', models.IntegerField()),
                ('reading_from', models.DateTimeField(default=datetime.datetime(2022, 10, 8, 13, 33, 6, 148734))),
                ('reading_to', models.DateTimeField(default=datetime.datetime(2022, 10, 8, 13, 33, 6, 148760))),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply', to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteStaticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lights', models.PositiveIntegerField()),
                ('total_watts', models.CharField(max_length=100)),
                ('aisle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
                ('aisle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleInfo')),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.BlockInfo')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.SensorData')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteLoadPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Total_Load', models.FloatField(blank=True, null=True)),
                ('r_volt', models.FloatField(blank=True, null=True)),
                ('y_volt', models.FloatField(blank=True, null=True)),
                ('b_volt', models.FloatField(blank=True, null=True)),
                ('r_current', models.FloatField(blank=True, null=True)),
                ('y_current', models.FloatField(blank=True, null=True)),
                ('b_current', models.FloatField(blank=True, null=True)),
                ('Supply_Source', models.CharField(blank=True, max_length=20, null=True)),
                ('Meter_Number', models.PositiveIntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('Updated_on', models.DateTimeField(blank=True, null=True)),
                ('Associated_Site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteBaseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_id', models.CharField(blank=True, max_length=50, null=True)),
                ('baseline_value', models.FloatField(default=0)),
                ('working_hours', models.FloatField(default=24)),
                ('baseline_from', models.DateField(blank=True, null=True)),
                ('baseline_to', models.DateField(blank=True, null=True)),
                ('aisle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
                ('associated_site_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyLoadSharePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_source', models.PositiveSmallIntegerField(choices=[(0, 'MAINS SUPPLY'), (1, 'DG 1'), (2, 'DG 2'), (3, 'DG 3'), (4, 'DG 4'), (5, 'DG 5')], default=0)),
                ('monthly_time_based_percentage', models.PositiveIntegerField(default=0)),
                ('monthly_energy_based_percentage', models.PositiveIntegerField(default=0)),
                ('for_month', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 10, 8, 13, 33, 6, 159139))),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='MeterSource',
            fields=[
                ('meter_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('meter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('power_source_1', models.PositiveIntegerField(blank=True, choices=[(0, 'Mains Supply'), (1, 'DG_1'), (2, 'DG_2'), (3, 'DG_3'), (4, 'DG_4')], null=True)),
                ('power_source_2', models.PositiveIntegerField(blank=True, choices=[(0, 'Mains Supply'), (1, 'DG_1'), (2, 'DG_2'), (3, 'DG_3'), (4, 'DG_4')], null=True)),
                ('meter_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Single Source'), (2, 'Dual Source')], null=True)),
                ('is_PS2_valid', models.BooleanField(default=False)),
                ('Associated_Site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='')),
                ('image_id', models.CharField(max_length=10)),
                ('which_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='HourlySiteReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_id', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_consumption', models.FloatField(default=0)),
                ('hourly_baseline_value', models.FloatField(default=0)),
                ('energy_saved', models.FloatField(default=0)),
                ('reading_from', models.DateTimeField(blank=True, null=True)),
                ('reading_to', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('aisle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
                ('associated_Site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='HomeGatewayId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgw_id', models.CharField(max_length=200)),
                ('rssh_port', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('monitoring_port', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('connected_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_to', to='wareApp.Site')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='wareApp.CustomerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, choices=[('GF', 'Ground Floor'), ('F1', 'First Floor'), ('F2', 'Second Floor'), ('F3', 'Third Floor'), ('F4', 'Fourth Floor'), ('F5', 'Fifth Floor')], max_length=30, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='FirePumpAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_volt', models.FloatField(blank=True, null=True)),
                ('y_volt', models.FloatField(blank=True, null=True)),
                ('b_volt', models.FloatField(blank=True, null=True)),
                ('Meter_Number', models.PositiveIntegerField(blank=True, null=True)),
                ('motor_status', models.IntegerField(blank=True, null=True)),
                ('auto_mode_updated_time', models.DateTimeField(blank=True, null=True)),
                ('manual_mode_updated_time', models.DateTimeField(blank=True, null=True)),
                ('power_source_updated_time', models.DateTimeField(blank=True, null=True)),
                ('off_mode_time', models.DateTimeField(blank=True, null=True)),
                ('motor_status_time', models.DateTimeField(blank=True, null=True)),
                ('Updated_on', models.DateTimeField(blank=True, null=True)),
                ('Site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
                ('aisleGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='FireEquipmentsSystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(blank=True, max_length=30, null=True)),
                ('categories', models.CharField(blank=True, max_length=30, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='FireEquipmentsSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNo', models.CharField(blank=True, max_length=30, null=True)),
                ('loaction', models.CharField(blank=True, max_length=30, null=True)),
                ('Warrenty_till', models.DateField(blank=True, null=True)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('next_service', models.DateField(blank=True, null=True)),
                ('deviceType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.FireEquipmentsSystemType')),
            ],
        ),
        migrations.CreateModel(
            name='Email_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_for', models.PositiveIntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Auto'), (3, 'PowerSource'), (4, 'OFF'), (5, 'MotorOn')], null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('deviceName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
                ('fire_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_for', models.PositiveIntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Auto'), (3, 'PowerSource'), (4, 'OFF'), (5, 'MotorOn')], null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('deviceName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.FirePumpAlarm')),
                ('fire_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='DailySiteReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_id', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_consumption', models.FloatField(default=0)),
                ('daily_baseline_value', models.FloatField(default=0)),
                ('energy_saved', models.FloatField(default=0)),
                ('reading_for', models.DateField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('aisle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
                ('associated_Site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site'),
        ),
        migrations.CreateModel(
            name='AlarmNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.PositiveIntegerField(choices=[(1, 'Super_Admin'), (2, 'Aviconn_Admin'), (3, 'Aviconn_Executive'), (4, 'Customer'), (5, 'Cust_Site_Manager')], default=1)),
                ('object_type', models.PositiveIntegerField(choices=[(0, 'No_Type'), (1, 'Sensor'), (3, 'Light'), (4, 'Meter'), (5, 'Gateway')], default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('Alarm_type', models.PositiveIntegerField(choices=[(0, 'Low_balance'), (1, 'Power_Cut'), (2, 'Pending Balance'), (3, 'Pending Request'), (4, 'Zero balance'), (5, 'Box opened'), (6, 'Internet_Gone'), (7, 'No meter reading')])),
                ('create_DateTime', models.DateTimeField(auto_now_add=True)),
                ('Alarm_priority', models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'High')], default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_do', models.CharField(blank=True, max_length=200, null=True)),
                ('off_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cloud_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.AddField(
            model_name='aislegroup',
            name='block_id',
            field=models.ManyToManyField(to='wareApp.BlockInfo'),
        ),
        migrations.AddField(
            model_name='aislegroup',
            name='floor',
            field=models.ManyToManyField(to='wareApp.Floor'),
        ),
        migrations.AddField(
            model_name='aislegroup',
            name='panel',
            field=models.ManyToManyField(to='wareApp.Panel'),
        ),
        migrations.AddField(
            model_name='aislegroup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site'),
        ),
    ]
