# Generated by Django 2.2.2 on 2022-10-08 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FansData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(blank=True, max_length=40, null=True)),
                ('totalFans', models.IntegerField(blank=True, null=True)),
                ('watt_80_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_100_Lights', models.IntegerField(blank=True, null=True)),
                ('totalWattFans', models.IntegerField(blank=True, null=True)),
                ('totalUnits', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 13, 35, 2, 195124)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 13, 35, 2, 185155)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 13, 35, 2, 185216)),
        ),
    ]
