# Generated by Django 2.2.2 on 2022-09-26 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(blank=True, max_length=40, null=True)),
                ('totalLights', models.IntegerField(blank=True, null=True)),
                ('watt_18_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_20_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_24_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_36_Lights', models.IntegerField(blank=True, null=True)),
                ('watt_40_Lights', models.IntegerField(blank=True, null=True)),
                ('totalWattLights', models.IntegerField(blank=True, null=True)),
                ('totalUnits', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 23, 16, 54, 504403)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 23, 16, 54, 484505)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 23, 16, 54, 484548)),
        ),
    ]
