# Generated by Django 2.2.2 on 2022-11-15 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0002_auto_20221008_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireequipmentssystem',
            name='assetNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 15, 5, 44, 29521)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 15, 5, 44, 18498)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 15, 5, 44, 18525)),
        ),
    ]
