# Generated by Django 2.2.2 on 2022-12-16 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0002_auto_20221216_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='baseline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 11, 8, 55, 159739)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 11, 8, 55, 138241)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 11, 8, 55, 138285)),
        ),
    ]
