# Generated by Django 2.2.2 on 2022-12-15 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0003_auto_20221115_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='baseline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 18, 35, 50, 32083)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 18, 35, 50, 22978)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 18, 35, 50, 23005)),
        ),
    ]
