# Generated by Django 2.2.2 on 2022-12-19 12:33

import datetime
from django.db import migrations, models


def _add_updated_by(apps, schema_editor):
    table_name = "wareApp_fireequipmentssystem"
    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
        if "updatedBy" in columns:
            return
    schema_editor.execute(
        'ALTER TABLE "wareApp_fireequipmentssystem" ADD COLUMN "updatedBy" varchar(25);'
    )


def _drop_updated_by(apps, schema_editor):
    table_name = "wareApp_fireequipmentssystem"
    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
        if "updatedBy" not in columns:
            return
    try:
        schema_editor.execute(
            'ALTER TABLE "wareApp_fireequipmentssystem" DROP COLUMN "updatedBy";'
        )
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0003_auto_20221216_1108'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='fireequipmentssystem',
                    name='updatedBy',
                    field=models.CharField(blank=True, max_length=25, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(_add_updated_by, _drop_updated_by),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 33, 9, 344058)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 33, 9, 323116)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 33, 9, 323180)),
        ),
    ]
