# Generated by Django 2.2.2 on 2022-12-19 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0003_auto_20221216_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireequipmentssystem',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 33, 9, 344058)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 33, 9, 323116)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 33, 9, 323180)),
        ),
    ]
