# Generated by Django 5.2.1 on 2025-05-30 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0007_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 22, 2, 14, 986629)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 22, 2, 14, 976005)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 22, 2, 14, 976046)),
        ),
    ]
