# Generated by Django 2.2.2 on 2023-03-28 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0007_auto_20230324_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_loadGraph_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='is_pf_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteloadpower',
            name='b_power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteloadpower',
            name='max_load',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siteloadpower',
            name='min_load',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siteloadpower',
            name='r_power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteloadpower',
            name='y_power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 16, 52, 21, 389920)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 16, 52, 21, 380430)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 16, 52, 21, 380459)),
        ),
    ]
