# Generated by Django 2.2.2 on 2023-03-28 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0008_auto_20230328_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 21, 31, 13, 449108)),
        ),
        migrations.AlterField(
            model_name='siteloadpower',
            name='max_load',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='siteloadpower',
            name='min_load',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 21, 31, 13, 439862)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 21, 31, 13, 439893)),
        ),
    ]
