# Generated by Django 5.2.1 on 2025-05-30 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0008_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 22, 8, 42, 512254)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 22, 8, 42, 501926)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 22, 8, 42, 501950)),
        ),
    ]
