# Generated by Django 5.2.1 on 2025-05-30 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0009_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 23, 11, 34, 130615)),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_manager',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 23, 11, 34, 120414)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 23, 11, 34, 120590)),
        ),
    ]
