# Generated by Django 2.2.2 on 2023-03-28 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0009_auto_20230328_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='aislegroup',
            name='b_phase_pf_threshold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='aislegroup',
            name='r_phase_pf_threshold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='aislegroup',
            name='y_phase_pf_threshold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 22, 54, 9, 375379)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 22, 54, 9, 364783)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 22, 54, 9, 364810)),
        ),
        migrations.CreateModel(
            name='PowerFactorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_phase_pf', models.FloatField(blank=True, default=0, null=True)),
                ('y_phase_pf', models.FloatField(blank=True, default=0, null=True)),
                ('b_phase_pf', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('aisle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
    ]
