# Generated by Django 2.2.2 on 2023-03-28 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0010_auto_20230328_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerfactordata',
            name='meter_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerfactordata',
            name='supply_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 23, 6, 14, 32911)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 23, 6, 14, 23648)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 23, 6, 14, 23675)),
        ),
    ]
