# Generated by Django 2.2.2 on 2023-03-28 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0011_auto_20230328_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='b_phase_pf_threshold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='r_phase_pf_threshold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='y_phase_pf_threshold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 23, 32, 52, 178845)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 23, 32, 52, 169346)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 23, 32, 52, 169375)),
        ),
    ]
