# Generated by Django 2.2.2 on 2023-03-29 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0012_auto_20230328_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 1, 0, 29, 920027)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 1, 0, 29, 908732)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 1, 0, 29, 908762)),
        ),
        migrations.CreateModel(
            name='MonthlyMinMaxLoadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_source', models.CharField(blank=True, max_length=20, null=True)),
                ('min_load', models.FloatField(blank=True, default=0, null=True)),
                ('min_load_created', models.DateTimeField(blank=True, null=True)),
                ('max_load', models.FloatField(blank=True, default=0, null=True)),
                ('max_load_created', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
    ]
