# Generated by Django 2.2.2 on 2023-03-30 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0013_auto_20230329_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='aislegroup',
            name='load_graph_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 1, 19, 48, 189756)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 1, 19, 48, 180356)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 1, 19, 48, 180382)),
        ),
    ]
