# Generated by Django 2.2.2 on 2023-03-31 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0014_auto_20230330_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='show_dg_mains_run_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 16, 53, 28, 46924)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 16, 53, 28, 31490)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 16, 53, 28, 31529)),
        ),
    ]
