# Generated by Django 2.2.2 on 2023-04-20 00:13

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0016_auto_20230407_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DGAlertsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_data', jsonfield.fields.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 0, 13, 24, 394049)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 0, 13, 24, 383507)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 0, 13, 24, 383532)),
        ),
    ]
