# Generated by Django 2.2.2 on 2023-04-26 21:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0017_auto_20230420_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 21, 44, 57, 89379)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 21, 44, 57, 79100)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 21, 44, 57, 79126)),
        ),
        migrations.CreateModel(
            name='DgFuelConsumptionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_consumption', models.FloatField(blank=True, default=0, null=True)),
                ('epoch_time', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
    ]
