# Generated by Django 2.2.2 on 2023-04-29 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0019_auto_20230429_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='show_fuel_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 15, 8, 35, 530173)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 15, 8, 35, 512584)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 15, 8, 35, 512622)),
        ),
    ]
