# Generated by Django 2.2.2 on 2023-04-30 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0020_auto_20230429_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='show_fuel_data',
            new_name='customer_visible_dg_fuel_data',
        ),
        migrations.AddField(
            model_name='site',
            name='customer_dg_fuel_visible_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='dg_fuel_system_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='partner_dg_fuel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 17, 45, 34, 385124)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 17, 45, 34, 374036)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 17, 45, 34, 374061)),
        ),
    ]
