# Generated by Django 2.2.2 on 2023-05-04 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0022_auto_20230502_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgunitconsumption',
            name='dg_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgunitconsumption',
            name='dg_fuel_consumption',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dgunitconsumption',
            name='dg_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 15, 47, 10, 906806)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 15, 47, 10, 895057)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 15, 47, 10, 895083)),
        ),
    ]
