# Generated by Django 2.2.2 on 2023-05-05 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0023_auto_20230504_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='aislegroup',
            name='on_sensor_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 10, 10, 32, 478534)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 10, 10, 32, 467019)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 10, 10, 32, 467046)),
        ),
        migrations.CreateModel(
            name='SensorAisleUnitConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_id', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_consumption', models.FloatField(default=0)),
                ('daily_baseline_value', models.FloatField(default=0)),
                ('energy_saved', models.FloatField(default=0)),
                ('reading_for', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('aisle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.AisleGroup')),
                ('associated_Site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
    ]
