# Generated by Django 2.2.2 on 2023-05-07 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0024_auto_20230505_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_history',
            name='email_for',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Auto'), (3, 'PowerSource'), (4, 'OFF'), (5, 'MotorOn'), (6, 'sensorByPass')], null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 15, 29, 5, 806624)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 15, 29, 5, 794982)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 15, 29, 5, 795011)),
        ),
    ]
