# Generated by Django 2.2.2 on 2023-05-19 00:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0027_auto_20230518_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_manager_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 0, 15, 25, 177783)),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 0, 15, 25, 165547)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 0, 15, 25, 165582)),
        ),
    ]
