# Generated by Django 2.2.2 on 2023-05-19 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0029_auto_20230519_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site_manager_name',
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 0, 18, 53, 913248)),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 0, 18, 53, 901785)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 0, 18, 53, 901812)),
        ),
    ]
