# Generated by Django 2.2.2 on 2023-06-07 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0031_auto_20230519_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='carbon_emission_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='is_carbon_emission_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 4, 48, 928600)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 4, 48, 912929)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 4, 48, 912958)),
        ),
    ]
