# Generated by Django 2.2.2 on 2023-06-07 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0032_auto_20230607_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 39, 0, 476971)),
        ),
        migrations.AlterField(
            model_name='site',
            name='carbon_emission_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 39, 0, 457998)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 39, 0, 458041)),
        ),
    ]
