# Generated by Django 2.2.2 on 2023-07-07 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0034_auto_20230707_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 11, 40, 25, 524109)),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'WH_Metering'), (2, 'WH_Energy_Saving'), (3, 'Fire_monitoring_system'), (4, 'FEMS'), (5, 'WH_SubMetering')], null=True),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 11, 40, 25, 502448)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 11, 40, 25, 502489)),
        ),
    ]
