# Generated by Django 2.2.2 on 2023-08-09 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0036_auto_20230720_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_hourly_data_visible_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 23, 19, 49, 470722)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 23, 19, 49, 456341)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 23, 19, 49, 456380)),
        ),
    ]
