# Generated by Django 2.2.2 on 2023-10-17 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0037_auto_20230809_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='b_phase_voltage_threshold_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='b_phase_voltage_threshold_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='dg_fuel_minimum_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='dg_fuel_tank_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='dg_overtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='r_phase_voltage_threshold_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='r_phase_voltage_threshold_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='show_voltage_alarms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='y_phase_voltage_threshold_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='y_phase_voltage_threshold_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 15, 31, 36, 638993)),
        ),
        migrations.AlterField(
            model_name='site',
            name='b_phase_pf_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='r_phase_pf_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='y_phase_pf_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 15, 31, 36, 626400)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 15, 31, 36, 626430)),
        ),
        migrations.CreateModel(
            name='SiteLoadParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.PositiveIntegerField(blank=True, choices=[(0, 'Voltage High'), (1, 'Voltage Low'), (2, 'Power Factor')], null=True)),
                ('power_source', models.CharField(blank=True, max_length=50, null=True)),
                ('meter_number', models.CharField(blank=True, max_length=10, null=True)),
                ('r_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('y_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('b_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
        migrations.CreateModel(
            name='NewAlarmsNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.PositiveIntegerField(blank=True, choices=[(0, 'High Voltage'), (1, 'Low Voltage'), (2, 'PF Bad Value Alarm'), (3, 'DG Overtime'), (4, 'DG Fuel Under Level'), (5, 'Mains Higher Consumption'), (6, 'Fuel Drain')], null=True)),
                ('alarm_priority', models.PositiveIntegerField(blank=True, choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], null=True)),
                ('power_source', models.CharField(blank=True, max_length=50, null=True)),
                ('r_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('y_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('b_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('off_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.Site')),
            ],
        ),
    ]
