# Generated by Django 2.2.2 on 2023-10-17 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0038_auto_20231017_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='newalarmsnotifications',
            name='run_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 23, 22, 39, 456876)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 23, 22, 39, 440948)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 23, 22, 39, 440974)),
        ),
    ]
