# Generated by Django 2.2.2 on 2023-10-18 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0039_auto_20231017_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_alarm_History_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 18, 46, 12, 884171)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 18, 46, 12, 868533)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 18, 46, 12, 868565)),
        ),
    ]
