# Generated by Django 2.2.2 on 2023-11-03 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0043_auto_20231019_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgunitconsumption',
            name='fetch_fuel_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 11, 39, 16, 514088)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 11, 39, 16, 495158)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 11, 39, 16, 495198)),
        ),
    ]
