# Generated by Django 5.2.1 on 2025-06-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0002_auto_20220926_2316'),
        ('wareApp', '0010_alter_monthlyloadsharepercentage_created_on_and_more'),
        ('wareApp', '0046_auto_20240305_1506'),
    ]

    operations = [
    ]
