# Generated by Django 5.2.1 on 2025-08-18 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0052_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyloaddata',
            name='is_bypassed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 12, 58, 3, 432887)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 12, 58, 3, 420188)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 12, 58, 3, 420217)),
        ),
    ]
