# Generated by Django 5.2.1 on 2025-08-20 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0053_hourlyloaddata_is_bypassed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dgalertsdata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 13, 0, 0, 873249)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 13, 0, 0, 855876)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 13, 0, 0, 855908)),
        ),
    ]
