# Generated by Django 5.2.1 on 2025-08-20 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0054_remove_dgalertsdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 13, 7, 32, 121346)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 13, 7, 32, 54117)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 13, 7, 32, 54154)),
        ),
    ]
