# Generated by Django 5.2.1 on 2025-11-24 15:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0057_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aislegroup',
            name='virtual_siteID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_site_ID', to='wareApp.site'),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 15, 45, 19, 163329)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 15, 45, 19, 119603)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 15, 45, 19, 119639)),
        ),
    ]
