# Generated by Django 5.2.1 on 2026-03-11 21:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0058_aislegroup_virtual_siteid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 11, 21, 40, 1, 387632)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 11, 21, 40, 1, 371763)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 11, 21, 40, 1, 371798)),
        ),
        migrations.CreateModel(
            name='SiteConsumptionPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_gateway_id', models.CharField(blank=True, max_length=200, null=True)),
                ('consumption_ping_time', models.DateTimeField(blank=True, null=True, verbose_name='Time of Consumption Ping')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.site')),
            ],
        ),
    ]
