# Generated by Django 5.2.1 on 2026-03-12 12:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0059_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 12, 1, 49, 627534)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 12, 1, 49, 610994)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 12, 1, 49, 611028)),
        ),
        migrations.CreateModel(
            name='SiteCeleryPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_gateway_id', models.CharField(blank=True, max_length=200, null=True)),
                ('leg_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Leg ID')),
                ('aisle_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aisle Group')),
                ('unit_consumption', models.FloatField(blank=True, null=True, verbose_name='Unit Consumption')),
                ('celery_ping_time', models.DateTimeField(blank=True, null=True, verbose_name='Time of Celery Ping')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.site')),
            ],
        ),
    ]
