# Generated by Django 5.2.1 on 2026-03-12 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0060_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconsumptionping',
            name='is_late_ping',
            field=models.BooleanField(default=False, verbose_name='Late by 10+ Mins'),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 22, 11, 36, 466178)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 22, 11, 36, 454258)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 22, 11, 36, 454285)),
        ),
    ]
