# Generated by Django 5.2.1 on 2026-03-12 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0061_siteconsumptionping_is_late_ping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 23, 13, 5, 642612)),
        ),
        migrations.AlterField(
            model_name='siteconsumptionping',
            name='is_late_ping',
            field=models.BooleanField(default=False, verbose_name='Late Ping Flag'),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 23, 13, 5, 631316)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 23, 13, 5, 631344)),
        ),
    ]
