# Generated by Django 5.2.1 on 2026-04-22 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0062_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 17, 39, 47, 234043)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 17, 39, 47, 179691)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 17, 39, 47, 179718)),
        ),
        migrations.AddIndex(
            model_name='dailysitereading',
            index=models.Index(fields=['associated_Site', 'leg_id', 'reading_for'], name='idx_daily_site_leg_date'),
        ),
    ]
