# Generated by Django 5.2.1 on 2026-04-29 18:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0065_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 18, 12, 43, 805631)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 18, 12, 43, 787740)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 18, 12, 43, 787780)),
        ),
        migrations.CreateModel(
            name='RecoveryMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('leg_id', models.CharField(blank=True, max_length=50, null=True)),
                ('power_source', models.IntegerField(blank=True, null=True)),
                ('recovery_type', models.CharField(choices=[('hourly_consumption', 'Hourly Consumption'), ('daily_consumption', 'Daily Consumption'), ('load_runtime', 'Load Runtime')], max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('response_received', 'Response Received'), ('applied', 'Applied'), ('verified', 'Verified'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='requested', max_length=30)),
                ('missing_from', models.DateTimeField()),
                ('missing_to', models.DateTimeField(blank=True, null=True)),
                ('expected_slots', models.IntegerField(default=0)),
                ('recovered_slots', models.IntegerField(default=0)),
                ('error_slots', models.IntegerField(default=0)),
                ('mqtt_request_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('mqtt_request_payload', models.TextField(blank=True, null=True)),
                ('mqtt_response_payload', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('aisle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wareApp.aislegroup')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wareApp.site')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['site', 'recovery_type', 'status'], name='idx_recovery_site_status'), models.Index(fields=['site', 'leg_id', 'recovery_type'], name='idx_recovery_site_leg'), models.Index(fields=['site', 'power_source', 'recovery_type'], name='idx_recovery_site_source'), models.Index(fields=['requested_at', 'is_active'], name='idx_recovery_active_time')],
            },
        ),
    ]
