# Generated by Django 5.2.1 on 2026-05-19 11:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0067_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmnotifications',
            name='aisle_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wareApp.aislegroup'),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 11, 25, 40, 276831)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 11, 25, 40, 261178)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 11, 25, 40, 261212)),
        ),
    ]
