# Generated by Django 5.2.1 on 2026-05-19 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0068_alarmnotifications_aisle_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmnotifications',
            name='Alarm_type',
            field=models.PositiveIntegerField(choices=[(0, 'Low_balance'), (1, 'Power_Cut'), (2, 'Pending Balance'), (3, 'Pending Request'), (4, 'Zero balance'), (5, 'Box opened'), (6, 'Internet_Gone'), (7, 'High Consumption'), (8, 'Low Consumption'), (9, 'No DG Run')]),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 21, 42, 37, 248315)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 21, 42, 37, 233288)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 21, 42, 37, 233316)),
        ),
    ]
