# Generated by Django 5.2.1 on 2026-05-22 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0069_alter_alarmnotifications_alarm_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 22, 16, 7, 19, 487228)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 22, 16, 7, 19, 428280)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 22, 16, 7, 19, 428307)),
        ),
        migrations.CreateModel(
            name='MeterDisconnectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_site_id', models.PositiveIntegerField(blank=True, null=True)),
                ('logged_site_id', models.PositiveIntegerField(blank=True, null=True)),
                ('meter_source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('meter_id', models.PositiveIntegerField()),
                ('meter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('meter_name', models.CharField(max_length=50)),
                ('status', models.CharField(default='disconnected', max_length=20)),
                ('port_id', models.CharField(blank=True, max_length=100, null=True)),
                ('detection_window_start', models.DateTimeField()),
                ('detection_window_end', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_log_path', models.CharField(blank=True, default='', max_length=255)),
                ('raw_log_line', models.TextField(blank=True, null=True)),
                ('synced_to_cloud', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('cloud_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-detection_window_end', 'meter_id'],
                'unique_together': {('meter_id', 'detection_window_start', 'detection_window_end')},
            },
        ),
    ]
