# Generated by Django 5.2.1 on 2026-08-17 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareApp', '0072_alter_monthlyloadsharepercentage_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgfuelconsumptiondata',
            name='fuel_level',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyloadsharepercentage',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 17, 14, 15, 41, 293016)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 17, 14, 15, 41, 276084)),
        ),
        migrations.AlterField(
            model_name='supplyloadtimeshare',
            name='reading_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 17, 14, 15, 41, 276128)),
        ),
    ]
