# Generated by Django 5.2.1 on 2026-09-15 19:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wareApp", "0081_add_dgunitconsumption_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dgfuelconsumptiondata",
            name="fuel_data_source",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="baseline_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monthlyloadsharepercentage",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 9, 15, 19, 28, 4, 780987)
            ),
        ),
        migrations.AlterField(
            model_name="supplyloadtimeshare",
            name="reading_from",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 9, 15, 19, 28, 4, 769568)
            ),
        ),
        migrations.AlterField(
            model_name="supplyloadtimeshare",
            name="reading_to",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 9, 15, 19, 28, 4, 769588)
            ),
        ),
        migrations.CreateModel(
            name="HomeGatewayStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=20, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=20, null=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "home_gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="wareApp.homegatewayid",
                    ),
                ),
            ],
        ),
    ]
